name: Trigger QA Tests On PR

on:
  pull_request:
    branches:
      - main
      - master
    types: [opened, synchronize, reopened]
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run tests against'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod

jobs:
  ping-qa-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.QA_REPO_TOKEN }}
          repository: SiddharthGupta25/demo-gh-qa 
          event-type: trigger-playwright-tests
          client-payload: |
            {
              "environment": "${{ github.event.inputs.environment || 'qa' }}",
              "pr_number": "${{ github.event.pull_request.number || 'manual' }}",
              "sha": "${{ github.event.pull_request.head.sha || github.sha }}"
            }