name: Run Playwright Tests

# Listen for the custom event from the Dev repo
on:
  repository_dispatch:
    types: [trigger-playwright-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QA Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.client_payload.environment }}" = "prod" ]; then
            echo "Running Production Tests..."
            npm run test:prod
          elsePa
            echo "Running QA Tests..."
            npm run test:qa
          fi